SET SERVEROUTPUT ON;

-- EMPACOTAMENTO DE OBJETOS
CREATE OR REPLACE PACKAGE PKG_RELATORIOS AS 
    PROCEDURE PRC_RELATORIO_CLIENTES_ENDERECOS;
    PROCEDURE PRC_RELATORIO_SERVICOS_RECOMPENSAS;
END PKG_RELATORIOS;
/