services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: challenge_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ../app/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - challenge_network

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: challenge_db
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - challenge_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"  
    depends_on:
      - api
    networks:
      - challenge_network

volumes:
  db_data:

networks:
  challenge_network:
